local helpers = require('spec.helpers')

describe('commands', function()
  before_each(function()
    helpers.reset_config()
  end)

  describe('setup', function()
    it('creates the :Render command', function()
      require('render.commands').setup()
      local cmds = vim.api.nvim_get_commands({})
      assert.is_not_nil(cmds.Render)
    end)
  end)

  describe('dispatch', function()
    it('does not error on :Render with no provider', function()
      require('render.commands').setup()
      assert.has_no.errors(function()
        vim.cmd('Render compile')
      end)
    end)

    it('does not error on :Render stop', function()
      require('render.commands').setup()
      assert.has_no.errors(function()
        vim.cmd('Render stop')
      end)
    end)

    it('does not error on :Render status', function()
      require('render.commands').setup()
      assert.has_no.errors(function()
        vim.cmd('Render status')
      end)
    end)
  end)
end)
